Resources:
  JitsiECSTaskRole: ${file(./serverless/iam/roles/jitsi-ecs-task-role.yml)}
  JitsiBastionSecurityGroupIngress: ${file(./serverless/security-groups/jitsi-bastion-sg-ingress.yml)}
  JitsiECSSecurityGroup: ${file(./serverless/security-groups/jitsi-ecs-sg.yml)}
  JitsiECSCluster: ${file(./serverless/ecs/clusters/jitsi-ecs-cluster.yml)}
  JitsiECSService: ${file(./serverless/ecs/services/jitsi-ecs-service.yml)}
  JitsiECSTaskDefinition: ${file(./serverless/ecs/task-definitions/jitsi-ecs-task-definition.yml)}
  JitsiECSLogGroup: ${file(./serverless/ecs/task-definitions/container-definitions/log-groups/jitsi-ecs-log-group.yml)}

  # Jitsi Load balancer
  JitsiALBLoadBalancer: ${file(./serverless/alb/load-balancers/jitsi-alb-elbv2-lb.yml)}
  JitsiALBTargetGroup: ${file(./serverless/alb/target-groups/jitsi-alb-tg.yml)}
  JitsiALBListener: ${file(./serverless/alb/listeners/jitsi-alb-listener.yml)}    

