Type: AWS::IAM::Role
Properties:
  RoleName: ${self:provider.stackName}-task-role
  AssumeRolePolicyDocument:
    Statement:
      - Effect: Allow
        Principal:
          Service: ecs-tasks.amazonaws.com
        Action: sts:AssumeRole
  ManagedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
